name: publish-curseforge

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build artifacts
        run: ./gradlew build
      - uses: BrycensRanch/read-properties-action@v1
        id: gradle_props
        with:
          file: gradle.properties
          all: true
      - name: Publish fabric artifacts
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 521126
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/${{ steps.gradle_props.outputs.archives_base_name }}-${{ github.event.release.tag_name }}.jar
            build/libs/${{ steps.gradle_props.outputs.archives_base_name }}-${{ github.event.release.tag_name }}-sources.jar

          version: ${{ github.event.release.tag_name }}

          version-type: beta
          loaders: |
            fabric
            quilt
          
          game-versions: ${{ steps.gradle_props.outputs.minecraft_version_range }}
          game-version-filter: releases
          
          dependencies: |
            fabric-api
            cloth-config

          java: |
            21

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip