name: publish-github

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt-hotspot'
          java-version: '21'
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build artifacts
        run: ./gradlew build
      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "build/libs/*"
          repo-token: ${{ secrets.GH_TOKEN }}
